### ISSUE TITLE
Build fails with resolve import "lit-html/directives/until.js" from "build/client/App.js".

### ISSUE THREAD

**Issue by OnurGumus** [alfonsogarciacaro/Lit.TodoMVC#5]
build fails with 
```
3 modules transformed.
[vite]: Rollup failed to resolve import "lit-html/directives/until.js" from "build/client/App.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "lit-html/directives/until.js" from "build/client/App.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (/Users/onurgumus/.nvm/versions/node/v16.9.0/lib/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:43253:19)
    at onwarn (/Users/onurgumus/.nvm/versions/node/v16.9.0/lib/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:43037:13)
    at Object.onwarn (/Users/onurgumus/.nvm/versions/node/v16.9.0/lib/node_modules/vite/node_modules/rollup/dist/shared/rollup.js:22994:13)
    at ModuleLoader.handleResolveId (/Users/onurgumus/.nvm/versions/node/v16.9.0/lib/node_modules/vite/node_modules/rollup/dist/shared/rollup.js:22338:26)
    at /Users/onurgumus/.nvm/versions/node/v16.9.0/lib/node_modules/vite/node_modules/rollup/dist/shared/rollup.js:22310:26
```

**Comment by alfonsogarciacaro** [comment]
Ok, this is probably related to #4. Are you using pnpm? I think I finally understand what it's happening, some places in Fable.Lit request things directly from `lit-html`, which should be there because it's a dependency of lit, but pnpm doesn't create symlinks for transitive dependencies so the bundler complains.

I will change Fable.Lit so everything is requested from "lit" package instead :+1: (a temporary work-around is to install lit-html as direct dependency for now).

**Comment by OnurGumus** [comment]
No I was using npm. Thanks for the quick fix.

**Comment by alfonsogarciacaro** [comment]
I've updated the repo to use latest Fable.Lit, can you please try again and reopen if you still have issues?

BTW, latest Fable.Lit also enables [scoped CSS](https://github.com/alfonsogarciacaro/Lit.TodoMVC/blob/d7e56a62ba001c20470c3e8e0d1e5f461b18be3e/src/Todos.fs#L214-L221) for components not using Shadow DOM.
